### ISSUE TITLE
add tms_ss_xtion (continued)

### ISSUE THREAD

**Issue by Masatomo-Onishi** [irvs/ros_tms#364]
<p>
This issue is the continuation of <a href="https://github.com/irvs/ros_tms/issues/333">issue333</a>.
</p>
<p>
I'm modifying this package for availability without local OpenNI2 libraries.
</p>

**Comment by robotpilot** [comment]
Please use the develop branch instead of master branch. The master branch is used for release version. I recommend above site for you.

"http://nvie.com/posts/a-successful-git-branching-model/

**Comment by robotpilot** [comment]
I installed libraries for OpenNI like libopenni2-dev, openni-utils and ros-indigo-openni-xxx, but I can't build your new packages. Please say your dependency package or development environment.

```sh
/home/rt/catkin_ws/src/ros_tms/tms_ss/tms_ss_xtion/estimateExtrinsicParameters/MyCalibration.cpp:15:20: fatal error: OpenNI.h: No such file or directory
#include 
^
compilation terminated.
[100%] Built target vicon_stream
make[2]: *** [ros_tms/tms_ss/tms_ss_xtion/CMakeFiles/estimateExtrinsicParameters.dir/estimateExtrinsicParameters/MyCalibration.cpp.o] Error 1
make[1]: *** [ros_tms/tms_ss/tms_ss_xtion/CMakeFiles/estimateExtrinsicParameters.dir/all] Error 2
make: *** [all] Error 2
Invoking "make -j12 -l12" failed
```

Also, I don't understand the CMakeLists.txt and package.xml of your new package.
It was all nonsense. Please check other packages, it serve as a reference to write the the CMakeLists.txt and package.xml.

**Comment by Masatomo-Onishi** [comment]
<p>
The cause of the problem that the build won't be done was because I forgot to put out an inclusion sentence of OpenNI.h. And I merged with the develop branch pulled from origin.
</p>
<p>
Additionally, I did refactoring of  the build setting files. Please check them again. If it is all green, accept this pull request.
</p>
<a herf="https://github.com/irvs/ros_tms/pull/368">https://github.com/irvs/ros_tms/pull/368</a>

**Comment by robotpilot** [comment]
Thanks for your effort. Your pull request successfully merged.
