### ISSUE TITLE
DAE Model improvement #1

### ISSUE THREAD

**Issue by Yuuta-watanabe** [irvs/ros_tms#422]
model created on rviz have some bad points.
so I will remake and update models in the following points.

>glass and wall picture 
>resize floor area & change picture
>put a two doors
>remove object obstacle 

I try it first(#1).

**Comment by robotpilot** [comment]
![problem_of_work_talbe](https://cloud.githubusercontent.com/assets/2698667/9296343/11011a0a-44c6-11e5-8913-1fed0d2452b2.png)

@Yuuta-watanabe ,
Please check the work_desk.dae files, it has a miss design.

**Comment by Yuuta-watanabe** [comment]
I have chage model position on the xacro.
chage position of kitchen , workdesk and, wordrobe.
![change_position](https://cloud.githubusercontent.com/assets/9208631/9372537/bebcfcf8-471a-11e5-8c0f-44092e4ba040.png)

**Comment by robotpilot** [comment]
Thanks for your efforts, @Yuuta-watanabe
